#!/bin/bash

# Specify client name as first argument
ovpnclientname=$1

# Specify server port as second argument
fwd_server_port=$2

# Specify client port as third argument
fwd_client_port=$3

# Specify protocol (tcp/udp) as 4th argument (default: tcp)
fwd_protocol=$4


if [ -z "$fwd_protocol" ]; then
  fwd_protocol="tcp"
fi

# Check if client name is empty
if [ -z "$ovpnclientname" ]; then
  # print message and exit
  echo "No client name specified!"
  echo "Usage: $0 client_name server_port client_port [protocol]"
  echo "Protocol is either tcp or udp"
  exit 1
fi

# Check if server port is empty
if [ -z "$fwd_server_port" ]; then
  # print message and exit
  echo "No server port specified!"
  echo "Usage: $0 client_name server_port client_port [protocol]"
  echo "Protocol is either tcp or udp"
  exit 1
fi

# Check if client port is empty
if [ -z "$fwd_client_port" ]; then
  # print message and exit
  echo "No client port specified!"
  echo "Usage: $0 client_name server_port client_port [protocol]"
  echo "Protocol is either tcp or udp"
  exit 1
fi

# include server configuration variables
source ovpn-server-config

# the variables below are set automatically
ovpnconfigfile=/etc/openvpn/$ovpnservername.conf
ovpnserverdir=/etc/openvpn/$ovpnservername
# get default route interface name
if [ -z "$default_iface_name" ]; then
  default_iface_name=`ip route | grep default | cut -d" " -f5`
fi
# get server external ip address (if not set manually above)
if [ -z "$ovpn_server_public_ip" ]; then
  ovpn_server_public_ip=`ifconfig $default_iface_name | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
fi


# if our custom openvpn server configuration file does not exist
if [ ! -f $ovpnconfigfile ]; then
  # print message and exit
  echo "OpenVPN server is NOT installed"
  exit 1
fi

# Append new forwarding parameters to client forwardings file
echo "${fwd_protocol} ${fwd_server_port} ${fwd_client_port}" >> $ovpnserverdir/fwd-$ovpnclientname

# If client is connected
if [ -f "/etc/openvpn/${ovpnservername}/ovpn-${ovpnclientname}-connected" ]; then
    ovpn_client_private_ip=`cat /etc/openvpn/${ovpnservername}/ovpn-${ovpnclientname}-connected`
    /sbin/iptables -t nat -A PREROUTING -p ${fwd_protocol} -d ${ovpn_server_public_ip} --dport ${fwd_server_port} -j DNAT --to-destination ${ovpn_client_private_ip}:${fwd_client_port}
    /sbin/iptables -A FORWARD -p ${fwd_protocol} -o ${ovpn_iface_name} -d ${ovpn_client_private_ip} --dport ${fwd_client_port} -j ACCEPT
    /sbin/iptables -I INPUT 1 -p ${fwd_protocol} --dport ${fwd_server_port} -j ACCEPT
fi

echo "Forwarding added."
